package com.medflow.entity;

public enum AuditAction {
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    PATIENT_VIEWED,
    PATIENT_UPDATED,
    DOCTOR_CREATED,
    APPOINTMENT_CREATED,
    APPOINTMENT_VIEWED,
    APPOINTMENT_CANCELLED,
    ENCOUNTER_CREATED,
    ENCOUNTER_VIEWED,
    DIAGNOSIS_CREATED,
    PRESCRIPTION_CREATED,
    PRESCRIPTION_VIEWED,
    SYMPTOM_PATTERN_PREDICTED
}
