CREATE TABLE encounters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    visit_date TIMESTAMP(6) NOT NULL,
    chief_complaint VARCHAR(500) NOT NULL,
    notes VARCHAR(2000),
    CONSTRAINT fk_encounters_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id),
    CONSTRAINT fk_encounters_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_encounters_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT uk_encounters_appointment UNIQUE (appointment_id)
);

CREATE INDEX idx_encounters_patient_id ON encounters (patient_id);
CREATE INDEX idx_encounters_doctor_id ON encounters (doctor_id);
CREATE INDEX idx_encounters_visit_date ON encounters (visit_date);
