CREATE TABLE diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id BIGINT NOT NULL,
    diagnosis_code VARCHAR(50) NOT NULL,
    diagnosis_name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT fk_diagnoses_encounter FOREIGN KEY (encounter_id) REFERENCES encounters (id)
);

CREATE INDEX idx_diagnoses_encounter_id ON diagnoses (encounter_id);
CREATE INDEX idx_diagnoses_diagnosis_code ON diagnoses (diagnosis_code);

CREATE TABLE prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id BIGINT NOT NULL,
    medication_name VARCHAR(150) NOT NULL,
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(100) NOT NULL,
    duration VARCHAR(100) NOT NULL,
    instructions VARCHAR(1000),
    CONSTRAINT fk_prescriptions_encounter FOREIGN KEY (encounter_id) REFERENCES encounters (id)
);

CREATE INDEX idx_prescriptions_encounter_id ON prescriptions (encounter_id);
